// @ts-nocheck
import * as __fd_glob_69 from "../content/docs/components/statuses/sonner.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/components/statuses/skeleton.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/components/statuses/progress.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/components/statuses/meter.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/components/statuses/empty.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/components/statuses/badge.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/components/statuses/alert.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/components/surfaces/separator.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/components/surfaces/card.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/components/overlays/tooltip.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/components/overlays/sheet.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/components/overlays/popover.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/components/overlays/drawer.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/components/overlays/dialog.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/components/navigation/tabs.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/components/navigation/pagination.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/components/navigation/link.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/components/navigation/breadcrumbs.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/components/media/carousel.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/components/media/avatar.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/components/layouts/sidebar.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/components/layouts/navbar.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/components/layouts/container.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/components/forms/text-field.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/components/forms/select.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/components/forms/search-field.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/components/forms/radio.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/forms/number-field.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/forms/input.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/forms/input-o-t-p.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/forms/field.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/forms/combo-box.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/forms/checkbox.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/date-and-time/time-field.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/date-and-time/range-calendar.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/date-and-time/date-range-picker.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/date-and-time/date-picker.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/date-and-time/date-field.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/date-and-time/calendar.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/drag-and-drop/drop-zone.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/collections/tree.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/collections/tag-group.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/collections/table.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/collections/list-box.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/collections/item.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/collections/grid-list.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/collections/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/collections/collapsible.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/collections/accordion.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/controls/toolbar.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/controls/switch.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/controls/slider.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/controls/kbd.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/controls/command.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/colors/color.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/charts/chart.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/buttons/toggle.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/buttons/toggle-group.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/buttons/file-trigger.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/buttons/button.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/getting-started/introduction.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/getting-started/client-side-routing.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/framework-guides/vite.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/framework-guides/nextjs.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/dark-mode/vite.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/dark-mode/remix.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/dark-mode/next-js.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/dark-mode/inertia-js.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/dark-mode/astro.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {}, {"dark-mode/astro.mdx": __fd_glob_0, "dark-mode/inertia-js.mdx": __fd_glob_1, "dark-mode/next-js.mdx": __fd_glob_2, "dark-mode/remix.mdx": __fd_glob_3, "dark-mode/vite.mdx": __fd_glob_4, "framework-guides/nextjs.mdx": __fd_glob_5, "framework-guides/vite.mdx": __fd_glob_6, "getting-started/client-side-routing.mdx": __fd_glob_7, "getting-started/installation.mdx": __fd_glob_8, "getting-started/introduction.mdx": __fd_glob_9, "components/buttons/button.mdx": __fd_glob_10, "components/buttons/file-trigger.mdx": __fd_glob_11, "components/buttons/toggle-group.mdx": __fd_glob_12, "components/buttons/toggle.mdx": __fd_glob_13, "components/charts/chart.mdx": __fd_glob_14, "components/colors/color.mdx": __fd_glob_15, "components/controls/command.mdx": __fd_glob_16, "components/controls/kbd.mdx": __fd_glob_17, "components/controls/slider.mdx": __fd_glob_18, "components/controls/switch.mdx": __fd_glob_19, "components/controls/toolbar.mdx": __fd_glob_20, "components/collections/accordion.mdx": __fd_glob_21, "components/collections/collapsible.mdx": __fd_glob_22, "components/collections/dropdown-menu.mdx": __fd_glob_23, "components/collections/grid-list.mdx": __fd_glob_24, "components/collections/item.mdx": __fd_glob_25, "components/collections/list-box.mdx": __fd_glob_26, "components/collections/table.mdx": __fd_glob_27, "components/collections/tag-group.mdx": __fd_glob_28, "components/collections/tree.mdx": __fd_glob_29, "components/drag-and-drop/drop-zone.mdx": __fd_glob_30, "components/date-and-time/calendar.mdx": __fd_glob_31, "components/date-and-time/date-field.mdx": __fd_glob_32, "components/date-and-time/date-picker.mdx": __fd_glob_33, "components/date-and-time/date-range-picker.mdx": __fd_glob_34, "components/date-and-time/range-calendar.mdx": __fd_glob_35, "components/date-and-time/time-field.mdx": __fd_glob_36, "components/forms/checkbox.mdx": __fd_glob_37, "components/forms/combo-box.mdx": __fd_glob_38, "components/forms/field.mdx": __fd_glob_39, "components/forms/input-o-t-p.mdx": __fd_glob_40, "components/forms/input.mdx": __fd_glob_41, "components/forms/number-field.mdx": __fd_glob_42, "components/forms/radio.mdx": __fd_glob_43, "components/forms/search-field.mdx": __fd_glob_44, "components/forms/select.mdx": __fd_glob_45, "components/forms/text-field.mdx": __fd_glob_46, "components/layouts/container.mdx": __fd_glob_47, "components/layouts/navbar.mdx": __fd_glob_48, "components/layouts/sidebar.mdx": __fd_glob_49, "components/media/avatar.mdx": __fd_glob_50, "components/media/carousel.mdx": __fd_glob_51, "components/navigation/breadcrumbs.mdx": __fd_glob_52, "components/navigation/link.mdx": __fd_glob_53, "components/navigation/pagination.mdx": __fd_glob_54, "components/navigation/tabs.mdx": __fd_glob_55, "components/overlays/dialog.mdx": __fd_glob_56, "components/overlays/drawer.mdx": __fd_glob_57, "components/overlays/popover.mdx": __fd_glob_58, "components/overlays/sheet.mdx": __fd_glob_59, "components/overlays/tooltip.mdx": __fd_glob_60, "components/surfaces/card.mdx": __fd_glob_61, "components/surfaces/separator.mdx": __fd_glob_62, "components/statuses/alert.mdx": __fd_glob_63, "components/statuses/badge.mdx": __fd_glob_64, "components/statuses/empty.mdx": __fd_glob_65, "components/statuses/meter.mdx": __fd_glob_66, "components/statuses/progress.mdx": __fd_glob_67, "components/statuses/skeleton.mdx": __fd_glob_68, "components/statuses/sonner.mdx": __fd_glob_69, });