import fs from "node:fs"
import path from "node:path"

const baseDir = path.resolve(__dirname, "../components")
const samplesDir = path.join(baseDir, "samples")
const blocksDir = path.join(baseDir, "blocks")
const outputMapFilePath = path.resolve(samplesDir, "generated/previews.ts")

function getAllFiles(dirPath: string, arrayOfFiles: string[] = []) {
  const files = fs.readdirSync(dirPath)
  for (const file of files) {
    const filePath = path.join(dirPath, file)
    if (fs.statSync(filePath).isDirectory()) {
      getAllFiles(filePath, arrayOfFiles)
    } else if (file.endsWith(".tsx")) {
      arrayOfFiles.push(filePath)
    }
  }
  return arrayOfFiles
}

function getAllBlocks(dirPath: string, arrayOfFiles: string[] = []) {
  const files = fs.readdirSync(dirPath)
  for (const file of files) {
    const filePath = path.join(dirPath, file)
    if (fs.statSync(filePath).isDirectory()) {
      getAllBlocks(filePath, arrayOfFiles)
    } else if (file.includes("page") || file.includes("layout")) {
      arrayOfFiles.push(filePath)
    }
  }
  return arrayOfFiles
}

const components = [...getAllFiles(samplesDir), ...getAllBlocks(blocksDir)]
  .filter((filePath) => !filePath.includes("/layouts") && !filePath.includes("/props")) // Exclude specific components
  .map((filePath) => {
    const relativePath = path.relative(baseDir, filePath).replace(/\\/g, "/").replace(".tsx", "")
    const key = relativePath.split("/").slice(1).join("/")
    const type = key.includes("page") || key.includes("layout") ? "blocks" : "samples"

    return {
      type,
      key
    }
  })

const previewsContent = `// This file is autogenerated by scripts/generate-previews.ts.
// Do not edit this file directly.
import { type LazyExoticComponent, lazy, type PropsWithChildren, type ReactElement } from "react"

export const previews: Record<string, { component: LazyExoticComponent<(props: PropsWithChildren) => ReactElement> }> = {
${components
  .map(
    (component) =>
      `"${component.key}": { component: lazy(() => import("@/components/${component.type}/${component.key}")) },`
  )
  .join("\n")}
};
`

fs.writeFileSync(outputMapFilePath, previewsContent)
