import fs from 'node:fs'
import path from 'node:path'

const baseDir = path.resolve(__dirname, '../components')
const samplesDir = path.join(baseDir, 'samples')
const uiDir = path.join(baseDir, 'ui')
const outputMapFilePath = path.resolve(samplesDir, 'generated/previews.ts')
const jsonOutputFilePath = path.resolve(samplesDir, 'generated/previews.json')

function getAllFiles(dirPath: string, arrayOfFiles: string[] = []) {
  const files = fs.readdirSync(dirPath)
  for (const file of files) {
    const filePath = path.join(dirPath, file)
    if (fs.statSync(filePath).isDirectory()) {
      getAllFiles(filePath, arrayOfFiles)
    } else if (file.endsWith('.tsx')) {
      arrayOfFiles.push(filePath)
    }
  }
  return arrayOfFiles
}

const components = [...getAllFiles(samplesDir), ...getAllFiles(uiDir)]
  .filter((filePath) => !filePath.includes('/how') && !filePath.includes('/props')) // Exclude specific components
  .reduce(
    (acc, filePath) => {
      const content = fs.readFileSync(filePath, 'utf8') // Read the file content
      const relativePath = path.relative(baseDir, filePath).replace(/\\/g, '/').replace('.tsx', '')
      const importPath = `@/components/${relativePath}`
      const key = relativePath.split('/').slice(1).join('/')
      const type = filePath.startsWith(samplesDir) ? 'docs' : 'ui' // Determine type based on folder path

      if (type === 'docs' && !filePath.includes('block/components')) {
        // @ts-expect-error no-type
        acc.tsComponents[key] = {
          component: importPath
        }
      }

      // @ts-expect-error no-type
      acc.jsonComponents[key] = {
        component: importPath,
        raw: content
      }

      return acc
    },
    { tsComponents: {}, jsonComponents: {} }
  )

const previewsContent = `// This file is autogenerated by scripts/create-previews.ts.
// Do not edit this file directly.
import { type LazyExoticComponent, lazy, type ReactElement } from 'react'

export const previews: Record<string, { component: LazyExoticComponent<() => ReactElement> }> = {
${Object.keys(components.tsComponents)
  .map((key) => `"${key}": { component: lazy(() => import("@/components/samples/${key}")) },`)
  .join('\n')}
};
`

fs.writeFileSync(outputMapFilePath, previewsContent)
fs.writeFileSync(jsonOutputFilePath, JSON.stringify(components.jsonComponents, null, 2))
