name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          scope: "@dq-alhq"
      - name: Install dependencies
        run: npm install --prefix packages
      - name: Build
        run: npm run build --prefix packages
      - name: Publish to npm
        run: npm publish --prefix packages --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
